# Generated by Django 4.0.3 on 2025-11-14 19:28

import apps.menu.models.menufreemodels.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_category)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['displayOrder'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نرخ برابری (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نرخ فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ\u200cهای ارز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح فارسی')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_image)),
                ('sound', models.FileField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_sound)),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)')),
                ('price_usd_cents', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (سنت)')),
                ('preparationTime', models.IntegerField(blank=True, help_text='زمان آماده\u200cسازی (دقیقه)', null=True)),
                ('created_by', models.CharField(choices=[('company', 'شرکت'), ('restaurant', 'رستوران')], default='restaurant', max_length=20, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'ordering': ['displayOrder'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customTitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سفارشی فارسی')),
                ('customTitle_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سفارشی انگلیسی')),
                ('customImage', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_menu_category)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['displayOrder'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان انگلیسی')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('english_name', models.CharField(blank=True, help_text='نام انگلیسی برای تولید اسلاگ', max_length=255, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیح فارسی')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='توضیح انگلیسی')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_restaurant_logo)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_restaurant_cover)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default='خالی', verbose_name='متن')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='آدرس انگلیسی')),
                ('openingTime', models.TimeField(blank=True, null=True)),
                ('closingTime', models.TimeField(blank=True, null=True)),
                ('minimumOrder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deliveryFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxRate', models.DecimalField(blank=True, decimal_places=2, default=9.0, max_digits=5, null=True)),
                ('isSeo', models.BooleanField(blank=True, default=False, null=True, verbose_name='ایا سئو شده')),
                ('expireDate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
            ],
            options={
                'ordering': ['displayOrder'],
                'abstract': False,
            },
        ),
    ]
