# Generated by Django 4.0.3 on 2025-10-21 17:33

from django.db import migrations, models
import django.db.models.deletion


# تابع ساده برای مسیر آپلود فایل‌ها
def upload_to(instance, filename):
    return f"uploads/{filename}"


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=upload_to)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['displayOrder'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=upload_to)),
                ('coverImage', models.ImageField(blank=True, null=True, upload_to=upload_to)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('openingTime', models.TimeField(blank=True, null=True)),
                ('closingTime', models.TimeField(blank=True, null=True)),
                ('minimumOrder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deliveryFee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('taxRate', models.DecimalField(blank=True, decimal_places=2, default=9.0, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['displayOrder'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customImage', models.ImageField(blank=True, null=True, upload_to=upload_to)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.category')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuCategories', to='menu.restaurant')),
            ],
            options={
                'verbose_name': 'Menu Category',
                'verbose_name_plural': 'Menu Categories',
                'ordering': ['displayOrder'],
                'unique_together': {('restaurant', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('displayOrder', models.IntegerField(blank=True, default=0, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=upload_to)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('preparationTime', models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('menuCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.menucategory')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.restaurant')),
            ],
            options={
                'ordering': ['displayOrder'],
                'abstract': False,
            },
        ),
    ]
