# Generated by Django 4.0.3 on 2025-10-22 15:29

import apps.menu.models.menufreemodels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='discount',
        ),
        migrations.AddField(
            model_name='food',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_sound),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_category),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_food_image),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='customImage',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_menu_category),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='coverImage',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_restaurant_cover),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.menu.models.menufreemodels.models.upload_to_restaurant_logo),
        ),
    ]
