# Generated by Django 4.0.3 on 2025-10-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_food_discount_food_sound_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
