# Generated by Django 4.0.3 on 2025-11-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created_by',
            field=models.CharField(choices=[('company', 'شرکت'), ('restaurant', 'رستوران')], default='restaurant', max_length=20, verbose_name='ایجاد شده توسط'),
        ),
    ]
