# Generated by Django 4.0.3 on 2025-11-04 11:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='خالی', verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='food',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='خالی', verbose_name='متن'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='خالی', verbose_name='متن'),
        ),
    ]
