# Generated by Django 4.0.3 on 2025-11-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_category_text_food_text_restaurant_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
        migrations.RemoveField(
            model_name='food',
            name='text',
        ),
    ]
