# Generated by Django 4.0.3 on 2025-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='english_name',
            field=models.CharField(blank=True, help_text='نام انگلیسی برای تولید اسلاگ', max_length=255, null=True, unique=True),
        ),
    ]
