# Generated by Django 4.0.3 on 2025-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_restaurant_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(blank=True, choices=[('fast_food', 'فست فود'), ('restaurant', 'رستوران'), ('cafe', 'کافه'), ('traditional', 'سنتی'), ('iranian', 'ایرانی'), ('international', 'بین\u200cالمللی'), ('pizza', 'پیتزا'), ('sandwich', 'ساندویچ'), ('breakfast', 'صبحانه'), ('seafood', 'غذای دریایی'), ('kebab', 'کباب'), ('vegetarian', 'گیاهخواری')], max_length=20, null=True),
        ),
    ]
