# Generated by Django 4.0.3 on 2025-10-27 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_category_category_type_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='food',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح انگلیسی'),
        ),
        migrations.AddField(
            model_name='food',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='customTitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سفارشی فارسی'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='customTitle_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سفارشی انگلیسی'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address_en',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس انگلیسی'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح انگلیسی'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان انگلیسی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح فارسی'),
        ),
        migrations.AlterField(
            model_name='food',
            name='preparationTime',
            field=models.IntegerField(blank=True, help_text='زمان آماده\u200cسازی (دقیقه)', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیح فارسی'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان فارسی'),
        ),
    ]
