# Generated by Django 4.0.3 on 2025-10-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_category_title_en_food_description_en_food_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='نرخ برابری (تومان)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نرخ فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ\u200cهای ارز',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='price_usd_cents',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (سنت)'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت (تومان)'),
        ),
    ]
