# Generated by Django 4.0.3 on 2025-11-14 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='عکس')),
                ('alt_text', models.CharField(max_length=200, verbose_name='متن جایگزین')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس گالری',
                'verbose_name_plural': 'گالری محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='کلید')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار')),
                ('slug', models.SlugField(max_length=100, verbose_name='اسلاگ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی\u200cهای محصول',
            },
        ),
    ]
