# Generated by Django 4.0.3 on 2025-11-14 19:28

import apps.user.validators.model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ایدی')),
                ('mobileNumber', models.CharField(max_length=11, unique=True, validators=[apps.user.validators.model.validate_iranian_mobile], verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('name', models.CharField(blank=True, max_length=60, null=True, verbose_name='نام')),
                ('family', models.CharField(blank=True, max_length=60, null=True, verbose_name='نام خانوادگی')),
                ('gender', models.CharField(choices=[('True', 'مرد'), ('False', 'زن')], default='True', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین اختصاصی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند (دسترسی ادمین)')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='کاربر اصلی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeCode', models.CharField(blank=True, max_length=16, null=True, verbose_name='کد فعال\u200cسازی')),
                ('expireCode', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضای کد')),
                ('isBan', models.BooleanField(default=False, verbose_name='بن شده/نشده')),
                ('isInfoFiled', models.BooleanField(default=False, verbose_name='وضعیت تکمیل اطلاعات')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceInfo', models.CharField(max_length=255, verbose_name='اطلاعات دستگاه')),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
