# Generated by Django 4.0.3 on 2025-10-18 12:11

import apps.user.validators.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobileNumber',
            field=models.CharField(max_length=11, unique=True, validators=[apps.user.validators.model.validate_iranian_mobile], verbose_name='شماره موبایل'),
        ),
    ]
