# Generated by Django 4.0.3 on 2025-11-14 19:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=30, verbose_name='نویسنده')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': '  نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('subject', models.CharField(max_length=30, verbose_name='موضوع')),
                ('image_name', models.ImageField(default='', upload_to=utils.FileUpload.upload_to, verbose_name='عکس اصلی')),
                ('view', models.IntegerField(verbose_name='ویو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('time_read', models.CharField(max_length=30, verbose_name='تایم مطالعه')),
                ('register_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('update_data', models.DateTimeField(auto_now_add=True, verbose_name='اپدیت شده')),
                ('description', models.TextField(blank=True, verbose_name='1توضیحات')),
                ('description2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='2توضیحات')),
                ('key_words', models.CharField(blank=True, max_length=1000, null=True, verbose_name='کلمات کلیدی')),
                ('slug', models.CharField(max_length=40, verbose_name='اسلاگ')),
                ('Auther_blog', models.ManyToManyField(to='blog.author', verbose_name='نویسنده مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Group_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='گروه ')),
                ('is_active', models.BooleanField(max_length=False, verbose_name='وضعیت')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': ' گروه مقاله',
                'verbose_name_plural': 'گروه های مقاله',
            },
        ),
        migrations.CreateModel(
            name='More_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qus', models.CharField(max_length=300, verbose_name='سوال')),
                ('answer', models.TextField(verbose_name='جواب سوال')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال بودن')),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_date', models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ اپدیت')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_faq', to='blog.blog', verbose_name='مقاله')),
            ],
        ),
        migrations.CreateModel(
            name='Meta_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_header', models.CharField(default='none', max_length=100, verbose_name='عنوان هدر')),
                ('description', models.TextField(blank=True, default='none', null=True, verbose_name='توضیحات')),
                ('keyword_list', models.TextField(blank=True, null=True, verbose_name='لیست کلید واژه')),
                ('og_title', models.CharField(default='none', max_length=100, verbose_name='عنوان هدر')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='وبلاگ')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='grop_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_of_blog', to='blog.group_blog', verbose_name='گروه مقاله'),
        ),
    ]
