# Generated by Django 4.0.3 on 2025-11-01 18:10

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=utils.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
    ]
