# Generated by Django 4.0.3 on 2025-10-31 09:52

from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordermenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfinaly', models.BooleanField(default=True, verbose_name='نهایی')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال')),
                ('image', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='عکس')),
                ('status', models.IntegerField(choices=[(1, 'پرداخت نشده'), (2, 'پرداخت شده'), (3, 'تایید شده'), (4, 'تحویل شده')], default=1, verbose_name='وضعیت')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant', verbose_name='کاربر')),
            ],
        ),
    ]
