# Generated by Django 4.0.3 on 2025-11-09 06:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordermenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isfinaly', models.BooleanField(default=True, verbose_name='نهایی')),
                ('isActive', models.BooleanField(default=False, verbose_name='فعال')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'پرداخت نشده'), (2, 'پرداخت شده'), (3, 'تایید شده'), (4, 'تحویل شده')], default=1, verbose_name='وضعیت سفارش')),
                ('is_seo_enabled', models.BooleanField(default=False, verbose_name='سئوی منو فعال شود؟')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant', verbose_name='رستوران')),
            ],
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_images/', verbose_name='عکس منو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ آپلود')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.ordermenu', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'عکس منو',
                'verbose_name_plural': 'عکس\u200cهای منو',
            },
        ),
    ]
