# Generated by Django 4.0.3 on 2025-11-01 18:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
        ('order', '0002_alter_ordermenu_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermenu',
            options={'verbose_name': 'سفارش منو', 'verbose_name_plural': 'سفارشات منو'},
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='image',
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 18, 4, 5, 431771, tzinfo=utc), null=True),
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 18, 4, 5, 431771, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant', verbose_name='رستوران'),
        ),
        migrations.CreateModel(
            name='OrdermenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس منو')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 18, 4, 5, 431771, tzinfo=utc), null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordermenu', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'عکس منو',
                'verbose_name_plural': 'عکس\u200cهای منو',
            },
        ),
    ]
