# Generated by Django 4.0.3 on 2025-11-01 18:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_ordermenu_options_remove_ordermenu_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 18, 10, 47, 614213, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 18, 10, 47, 614213, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='ordermenuimage',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 1, 18, 10, 47, 614213, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='ordermenuimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس منو'),
        ),
    ]
