# Generated by Django 4.0.3 on 2025-11-01 18:25

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermenu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermenu',
            options={},
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='status',
        ),
        migrations.RemoveField(
            model_name='ordermenu',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ordermenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
        migrations.DeleteModel(
            name='OrdermenuImage',
        ),
    ]
