# Generated by Django 4.0.3 on 2025-11-02 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_ordermenu_options_remove_ordermenu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu_images/', verbose_name='عکس منو')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ آپلود')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.ordermenu', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'عکس منو',
                'verbose_name_plural': 'عکس\u200cهای منو',
            },
        ),
    ]
