# Generated by Django 4.0.3 on 2025-11-02 06:20

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_ordermenu_image_menuimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'پرداخت نشده'), (2, 'پرداخت شده'), (3, 'تایید شده'), (4, 'تحویل شده')], default=1, verbose_name='وضعیت سفارش'),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
