# Generated by Django 4.0.3 on 2025-11-02 12:13

from django.db import migrations, models
import django.utils.timezone
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordermenu_status_alter_ordermenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
