# Generated by Django 4.0.3 on 2025-11-02 12:14

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_ordermenu_create_at_alter_ordermenu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermenu',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
