# Generated by Django 4.0.3 on 2025-11-03 13:02

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_ordermenu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
