# Generated by Django 4.0.3 on 2025-11-06 12:18

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_ordermenu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermenu',
            name='is_seo_enabled',
            field=models.BooleanField(default=False, verbose_name='سئوی منو فعال شود؟'),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='عکس'),
        ),
    ]
