# Generated by Django 4.0.3 on 2025-10-31 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0002_alter_ordermenu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('updateAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('description', models.TextField(verbose_name='توضیحات پرداخت')),
                ('isFinaly', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('statusCode', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت پرداخت')),
                ('refId', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری پرداخت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peyment_customer', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peyment_order', to='order.ordermenu', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت ها',
            },
        ),
    ]
