# Generated by Django 4.0.3 on 2025-11-14 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پلن')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پلن')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت پلن')),
                ('expiryDays', models.IntegerField(default=30, verbose_name='انقضای پلن (روز)')),
                ('isActive', models.BooleanField(default=True, verbose_name='فعال')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('isFavorit', models.BooleanField(default=False, verbose_name='محبوب ترین')),
            ],
            options={
                'verbose_name': 'پلن',
                'verbose_name_plural': 'پلن\u200cها',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ویژگی')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار ویژگی')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('isAvailable', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'ویژگی پلن',
                'verbose_name_plural': 'ویژگی\u200cهای پلن',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('finalPrice', models.PositiveIntegerField(verbose_name='قیمت نهایی')),
                ('isPaid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('paidAt', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('expiryDate', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('trackingCode', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='plan.plan', verbose_name='پلن')),
            ],
            options={
                'verbose_name': 'سفارش پلن',
                'verbose_name_plural': 'سفارشات پلن',
                'ordering': ['-createdAt'],
            },
        ),
    ]
