# Generated by Django 4.0.3 on 2025-11-14 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='plan.plan', verbose_name='پلن'),
        ),
        migrations.AddIndex(
            model_name='planorder',
            index=models.Index(fields=['user', 'createdAt'], name='plan_planor_user_id_432a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='planorder',
            index=models.Index(fields=['isPaid', 'createdAt'], name='plan_planor_isPaid_eb5f72_idx'),
        ),
    ]
