# Generated by Django 4.0.3 on 2025-11-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='content/images/', verbose_name='عکس')),
                ('direction', models.CharField(choices=[('ltr', 'چپ به راست'), ('rtl', 'راست به چپ')], default='ltr', max_length=3, verbose_name='جهت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'بلاک محتوا',
                'verbose_name_plural': 'بلاک\u200cهای محتوا',
                'ordering': ['-created_at'],
            },
        ),
    ]
