# Generated by Django 4.0.3 on 2025-11-14 19:28

import ckeditor_uploader.fields
from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextImageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='متن')),
                ('image', models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر')),
                ('image_position', models.CharField(choices=[('left', 'تصویر در چپ'), ('right', 'تصویر در راست')], default='right', max_length=5, verbose_name='موقعیت تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'باکس متن و تصویر',
                'verbose_name_plural': 'باکس\u200cهای متن و تصویر',
                'ordering': ['order'],
            },
        ),
    ]
