# Generated by Django 4.0.3 on 2025-11-03 13:25

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_textimageblock_delete_contentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimageblock',
            name='image',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
