# Generated by Django 4.0.3 on 2025-11-04 12:03

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_textimageblock_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textimageblock',
            name='image',
            field=models.FileField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر'),
        ),
    ]
